[build]
  publish = "_site"
  command = """
    wget -q https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.549/quarto-1.4.549-linux-amd64.tar.gz && \
    mkdir -p /opt/build/repo/.quarto && \
    tar -xzf quarto-1.4.549-linux-amd64.tar.gz -C /opt/build/repo/.quarto && \
    export PATH="/opt/build/repo/.quarto/quarto-1.4.549/bin:$PATH" && \
    quarto render
  """

[build.environment]
  NODE_VERSION = "18"